// src/pages/manager/visit-briefing.tsx
// WIREFRAME — Visit Briefing Pack (V2)
// Mobile view, two states: pre-visit (read briefing) and active (observation prompts)
// Data entity: VisitBriefing — generated by visit_briefing.generate job

import { MOCK_MANAGER, MOCK_VISIT } from '@/data/mock'

// ─── DATA THIS PAGE READS ─────────────────────────────────────────────────────
// GET /api/visit-briefings/:visit_plan_id
//   → VisitBriefing with all sections

// ─── DATA THIS PAGE WRITES ────────────────────────────────────────────────────
// PATCH /api/visits/:id { status: 'active' }
//   → sets visit_plan.status = active
//   → sets visit_briefing.visit_started_at = now()
//   → focus_areas become capture prompts in observation form

const MOCK_BRIEFING = {
  id: 'vb-001',
  visit_plan_id: MOCK_VISIT.id,
  worksite_id: 'ws-001',
  worksite_name: 'Riverside Tower',
  manager_name: MOCK_MANAGER.name,
  generated_at: new Date(Date.now() - 3600000 * 36).toISOString(), // 36h ago
  snapshot_expires_at: new Date(Date.now() + 3600000 * 12).toISOString(), // 12h remaining
  viewed_at: null,
  visit_started_at: null,

  // AI-generated content
  headline: 'Six near-misses in 28 days — spotter management is the issue to investigate on site today.',
  site_reading: 'Riverside Tower is showing the highest atrophy in the region at 79. The near-miss cluster is real and confirmed across 4 sites — this isn\'t an observation volume problem, it\'s a systemic control gap. Two investigations are open. No manager visit in 24 days.',
  watch_for: 'Watch whether spotters are actively confirmed in position before reversing operations begin — not just assumed. If you see a reversing movement without eye contact between operator and spotter, that\'s the gap in practice.',
  open_items: '2 open investigations (INC-0088, INC-0091). 3 corrective actions overdue — oldest is 8 days. One action assigned to J. Reyes around STMP update is the priority.',
  fw_context: 'Recent intelligence at this site consistently points to Management Systems gaps at Compliant maturity — look for procedure content gaps, not just whether controls are named in the PTW.',

  site_snapshot: { atrophy_score: 79, days_since_last_obs: 18, near_miss_30d: 6, open_investigations: 2 },

  focus_areas: [
    { topic: 'Spotter positioning during reversing', rationale: 'Primary pattern driving the regional insight — 6 near-misses in 28 days', source: 'trend', evidence: '6 near-misses across 4 sites · CI-042 approved' },
    { topic: 'PTW sign-on — workers reading conditions before starting', rationale: 'Practice atrophy — no PTW observation logged in 14 days', source: 'ai', evidence: 'No PTW observation in 14 days' },
    { topic: 'Hot work pre-task checklist', rationale: 'Open investigation INC-0088 — fire watch scope definition gap', source: 'investigation', evidence: 'Open investigation INC-0088' },
  ],

  active_insights: [
    { id: 'ci-042', title: 'Spotter management — 6 near-misses · North Region', work_type: 'Heavy Vehicle', approved_at: '2 days ago', fw_factor: 'management_systems' },
  ],

  open_actions: [
    { description: 'Update STMP — spotter positioning requirements', assigned_to: 'J. Reyes', due_date: 'Yesterday', days_overdue: 1, status: 'overdue' },
    { description: 'Add reversing camera to vehicle pre-start', assigned_to: 'M. Chen', due_date: 'In 6 days', days_overdue: 0, status: 'open' },
  ],
}

export default function VisitBriefingPage() {
  const briefing = MOCK_BRIEFING
  const isStale = new Date(briefing.snapshot_expires_at) < new Date()
  const isActive = briefing.visit_started_at !== null

  const sourceColors: Record<string, string> = { trend: '#dc2626', investigation: '#d97706', ai: '#7635DC' }

  return (
    <div style={{ fontFamily: 'monospace', maxWidth: 480, margin: '0 auto', background: '#fafafa', minHeight: '100vh' }}>

      {/* HEADER */}
      <div style={{ background: '#1a1a2e', color: '#e8ecf8', padding: '12px 16px' }}>
        <div style={{ fontSize: 10, opacity: 0.4, marginBottom: 4 }}>WIREFRAME · /manager/visit-briefing/:visit_plan_id</div>
        <div style={{ fontSize: 15, fontWeight: 700 }}>{briefing.worksite_name}</div>
        <div style={{ fontSize: 11, opacity: 0.6, marginTop: 2 }}>
          Visit Briefing · {isActive ? '🟢 Visit Active' : 'Pre-visit'} · Generated 36h ago
        </div>
        {isStale && (
          <div style={{ marginTop: 6, background: 'rgba(217,119,6,0.2)', border: '1px solid rgba(217,119,6,0.4)', borderRadius: 4, padding: '4px 8px', fontSize: 10, color: '#fbbf24' }}>
            ⚠ Briefing may be stale — generated {'>'}48h ago. Pull to refresh.
          </div>
        )}
      </div>

      {/* ENTITY READS */}
      <div style={{ background: '#f0f0ff', borderBottom: '1px solid #d0d0ff', padding: '5px 12px' }}>
        <div style={{ fontSize: 9, color: '#444' }}>
          <span style={{ background: '#5555aa', color: 'white', padding: '1px 5px', borderRadius: 2, marginRight: 4 }}>VisitBriefing</span>
          GET /api/visit-briefings/{briefing.visit_plan_id}
        </div>
      </div>

      <div style={{ padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 10 }}>

        {/* HEADLINE */}
        <div style={{ background: '#1a1a2e', color: 'white', borderRadius: 7, padding: '12px 14px' }}>
          <div style={{ fontSize: 9, opacity: 0.5, marginBottom: 4, letterSpacing: 1, textTransform: 'uppercase' }}>headline · VisitBriefing.headline</div>
          <div style={{ fontSize: 13, fontWeight: 600, lineHeight: 1.5 }}>{briefing.headline}</div>
        </div>

        {/* SITE SNAPSHOT TILES */}
        <Block label="Site Snapshot · VisitBriefing.site_snapshot">
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
            <Tile label="Atrophy Score" value={briefing.site_snapshot.atrophy_score} color="#dc2626" />
            <Tile label="Days no obs" value={briefing.site_snapshot.days_since_last_obs} color="#d97706" />
            <Tile label="Near-miss 30d" value={briefing.site_snapshot.near_miss_30d} color="#d97706" />
            <Tile label="Open invest." value={briefing.site_snapshot.open_investigations} color="#d97706" />
          </div>
        </Block>

        {/* FOCUS AREAS */}
        <Block label="Focus Areas · VisitBriefing.focus_areas[]" highlight>
          {briefing.focus_areas.map((f, i) => (
            <div key={i} style={{ marginBottom: 10, paddingBottom: 10, borderBottom: i < briefing.focus_areas.length - 1 ? '1px dashed #e0e0e0' : 'none' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 3 }}>
                <div style={{ fontSize: 12, fontWeight: 600, flex: 1 }}>{f.topic}</div>
                <span style={{ fontSize: 9, background: sourceColors[f.source] + '20', color: sourceColors[f.source], padding: '1px 6px', borderRadius: 3, flexShrink: 0, marginLeft: 8 }}>{f.source}</span>
              </div>
              <div style={{ fontSize: 10, color: '#888', marginBottom: 3 }}>{f.evidence}</div>
              <div style={{ fontSize: 11, color: '#555', fontStyle: 'italic' }}>{f.rationale}</div>
            </div>
          ))}
          {isActive && (
            <div style={{ background: '#f0fff0', border: '1px solid #aaffaa', borderRadius: 4, padding: '6px 8px', fontSize: 10, color: '#166534' }}>
              ↑ Active state: these topics are now shown as capture prompts in the observation form
            </div>
          )}
        </Block>

        {/* SITE READING */}
        <Block label="Site Reading · VisitBriefing.site_reading">
          <div style={{ fontSize: 12, color: '#333', lineHeight: 1.6 }}>{briefing.site_reading}</div>
        </Block>

        {/* FW CONTEXT */}
        <Block label="Forge Works Signal · VisitBriefing.fw_context">
          <div style={{ fontSize: 12, color: '#5555aa', fontStyle: 'italic', lineHeight: 1.6 }}>{briefing.fw_context}</div>
          <div style={{ fontSize: 10, color: '#888', marginTop: 4 }}>Aggregated from fw_factors[] across recent intelligence at this site</div>
        </Block>

        {/* WATCH FOR */}
        <Block label="Watch For · VisitBriefing.watch_for">
          <div style={{ fontSize: 12, color: '#333', lineHeight: 1.6 }}>{briefing.watch_for}</div>
        </Block>

        {/* OPEN ACTIONS */}
        <Block label="Open Actions · VisitBriefing.open_actions[]">
          {briefing.open_actions.map((a, i) => (
            <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px dashed #e0e0e0', fontSize: 11 }}>
              <div>
                <div style={{ fontWeight: 600, marginBottom: 2 }}>{a.description}</div>
                <div style={{ fontSize: 10, color: '#888' }}>{a.assigned_to} · {a.due_date}</div>
              </div>
              <span style={{ fontSize: 9, padding: '2px 6px', borderRadius: 3, flexShrink: 0, alignSelf: 'flex-start', background: a.status === 'overdue' ? '#fee2e2' : '#f0f0f0', color: a.status === 'overdue' ? '#dc2626' : '#666' }}>
                {a.status === 'overdue' ? `${a.days_overdue}d overdue` : a.status}
              </span>
            </div>
          ))}
        </Block>

        {/* OPEN ITEMS */}
        <Block label="Open Items · VisitBriefing.open_items">
          <div style={{ fontSize: 12, color: '#333', lineHeight: 1.6 }}>{briefing.open_items}</div>
        </Block>

        {/* START VISIT */}
        {!isActive && (
          <div>
            <div style={{ background: '#059669', color: 'white', borderRadius: 6, padding: '12px', textAlign: 'center', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
              Start Visit
            </div>
            <div style={{ fontSize: 10, color: '#888', textAlign: 'center', marginTop: 4 }}>
              PATCH /api/visits/:id {'{'}status: active{'}'}<br/>
              Sets visit_briefing.visit_started_at = now()
            </div>
          </div>
        )}

      </div>

      {/* BOTTOM NAV */}
      <div style={{ borderTop: '1px solid #eee', padding: '10px 14px', display: 'flex', gap: 8, background: 'white', position: 'sticky', bottom: 0 }}>
        {['Visits', 'Capture', 'Insights', 'Records'].map(tab => (
          <div key={tab} style={{ flex: 1, textAlign: 'center', fontSize: 10, padding: '6px 0', background: tab === 'Visits' ? '#1a1a2e' : '#f5f5f5', color: tab === 'Visits' ? 'white' : '#666', borderRadius: 4 }}>{tab}</div>
        ))}
      </div>
    </div>
  )
}

// ─── PRIMITIVES ───────────────────────────────────────────────────────────────

function Block({ label, children, highlight = false }: { label: string; children: React.ReactNode; highlight?: boolean }) {
  return (
    <div style={{ background: 'white', border: `${highlight ? 2 : 1}px solid ${highlight ? '#1a1a2e' : '#e0e0e0'}`, borderRadius: 6, overflow: 'hidden' }}>
      <div style={{ background: highlight ? '#1a1a2e' : '#f5f5f5', padding: '5px 10px', fontSize: 9, color: highlight ? 'rgba(255,255,255,0.6)' : '#888', fontWeight: 600 }}>{label}</div>
      <div style={{ padding: '10px 12px' }}>{children}</div>
    </div>
  )
}

function Tile({ label, value, color }: { label: string; value: any; color: string }) {
  return (
    <div style={{ background: '#f9f9f9', border: '1px solid #eee', borderRadius: 5, padding: '8px', textAlign: 'center' }}>
      <div style={{ fontSize: 20, fontWeight: 700, color }}>{value}</div>
      <div style={{ fontSize: 9, color: '#888', marginTop: 2 }}>{label}</div>
    </div>
  )
}
